#!/bin/bash

# Vscode extensions
cp -R ~/.vscode backups

# Vscode settings
cp -R ~/Library/Application\ Support/Code/User/settings.json backups/Code/User/settings.json

cp -R ~/.config/karabiner backups

cp backups/.zshrc ~/.zshrc

cp backups/.vimrc ~/.vimrc
