#!/bin/bash

# Install multiple apps with macapps
curl -s 'https://api.macapps.link/en/firefox-chrome-openoffice-sublime-vscode-docker-postman-iterm-unarchiver-flux-spectacle-spotify-vlc-gimp-skype-slack-whatsapp' | sh

#Install homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew install postgresql

brew tap heroku/brew && brew install heroku

brew install rbenv

brew install nodenv

brew install pyenv

brew cask install karabiner-elements

brew install zsh zsh-completions zsh-syntax-highlighting

# Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

brew tap sambadevi/powerlevel9k && brew install powerlevel9k

brew tap homebrew/cask-fonts && brew cask install font-hack-nerd-font

./pimp
